kafka:
  producer:
    bootstrap.servers: localhost:9092
    acks: all
    retries: 0
    batch.size: 16384
    linger.ms: 1
    buffer.memory: 33554432
    key.serializer: org.apache.producer.common.serialization.StringSerializer
    value.serializer: org.apache.producer.common.serialization.StringSerializer

  consumer:
    bootstrap.servers: localhost:9092
    group.id: config
    enable.auto.commit: false
    heartbeat.interval.ms: 1000
    key.deserializer: org.apache.producer.common.serialization.StringDeserializer
    value.deserializer: org.apache.producer.common.serialization.StringDeserializer
